#config_version=6
# config/config_ball_devices.yaml

ball_devices:
    bd_plunger:
      ball_switches: s_31_plunger_lane
      mechanical_eject: true
      eject_timeouts: 4s
      eject_coil: c_01_plunger
      eject_targets: playfield
#---------------------------------------
    bd_trough:
      ball_switches: s_24_trough_1, s_25_trough_2, s_26_trough_3, s_27_trough_4, s_28_trough_5, s_29_trough_6
      eject_coil: c_02_trough_eject
      eject_targets: bd_plunger
      tags: trough, home, drain
      jam_switch: s_30_trough_jam
#---------------------------------------
    bd_left_vuk:
      ball_switches: s_81_saucer_left
      eject_coil: c_29_saucer_left
      mechanical_eject: true
      eject_targets: playfield
      # recommended defaults/safety
      confirm_eject_type: target
      eject_timeouts: 3s
#---------------------------------------
    bd_right_vuk:
      ball_switches: s_59_saucer_right
      eject_coil: c_15_saucer_right
      mechanical_eject: true
      eject_targets: playfield
      # recommended defaults/safety
      confirm_eject_type: target
      eject_timeouts: 3s
      

