#config_version=6
# ------------------------
# CONFIG:FLIPPERS
# ------------------------     
flippers:
    right_flipper:
        main_coil: c_05_right_flipper_main
        hold_coil: c_06_right_flipper_hold
        activation_switch: s_16_right_flipper
        disable_events: game_ending
        enable_events: ball_started
    left_flipper:
        main_coil: c_03_left_flipper_main
        hold_coil: c_04_left_flipper_hold
        activation_switch: s_08_left_flipper
        disable_events: game_ending
        enable_events: ball_started
    right_top_flipper:
        main_coil: c_10_right_top_flipper_main
        hold_coil: c_09_right_top_flipper_hold
        activation_switch: s_17_right_flipper_upper
        disable_events: game_ending
        enable_events: ball_started 
# ------------------------
# CONFIG:COILS:AUTOFIRE
# ------------------------     
autofire_coils:
    ac_sling_left:
        coil: c_07_left_sling
        switch: s_37_left_sling
        disable_events: ball_ending
        enable_events: ball_started
    ac_sling_right:
        coil: c_08_right_sling
        switch: s_34_right_sling
        disable_events: ball_ending
        enable_events: ball_started
    ac_pop_1:
        coil: c_14_pop_bumper_left
        switch: s_58_pop_bumper_left
        disable_events: ball_ending
        enable_events: ball_started
    ac_pop_2:
        coil: c_12_pop_bumper_center
        switch: s_57_pop_bumper_center
        disable_events: ball_ending
        enable_events: ball_started
    ac_pop_3:
        coil: c_13_pop_bumper_right
        switch: s_56_pop_bumper_right
        disable_events: ball_ending
        enable_events: ball_started