#config_version=6
# ------------------------
# CONFIG:COILS
# ------------------------  
coils:
# --------------------------------------------------------------------------------------------------------------------
# CONFIG:COILS - PLAYFIELD BOTTOM THIRD
# 3208 pf2
# J4
# ------------------------
    c_01_plunger:
        number: pf2-0
        default_pulse_ms: 10
    c_02_trough_eject:
        number: pf2-1
        default_pulse_ms: 30
    
    
    c_03_left_flipper_main:
        number: pf2-3
        default_pulse_ms: 1
        allow_enable: false
    c_04_left_flipper_hold:
        number: pf2-2
        allow_enable: true
        default_hold_power: 0.1  
    c_05_right_flipper_main:
        number: pf2-4
        default_pulse_ms: 25
        allow_enable: false
    c_06_right_flipper_hold:
        number: pf2-5
        allow_enable: true
        default_hold_power: 0.35
    
    
    c_07_left_sling:
        number: pf2-7
        default_pulse_ms: 8
    c_08_right_sling:
        number: pf2-6
        default_pulse_ms: 8
#
# --------------------------------------------------------------------------------------------------------------------
#
#
# --------------------------------------------------------------------------------------------------------------------
# CONFIG:COILS - PLAYFIELD Upper Node 1
# 1616 pf1
# J3 - 8 Coils
# C_9 to C_16
# ------------------------
    c_09_right_top_flipper_hold:
        number: pf1-0
        allow_enable: true
        default_hold_power: 0.35
    c_10_right_top_flipper_main:
        number: pf1-1
        default_pulse_ms: 25
        allow_enable: false
        
#    c_11_SPARE:
#        number: pf1-2
#        default_pulse_ms: 1
# ------------------------
# CONFIG:COILS - POP BUMPERS
# ------------------------ 
    c_12_pop_bumper_center:
        number: pf1-3
        default_pulse_ms: 10
    c_13_pop_bumper_right:
        number: pf1-4
        default_pulse_ms: 10
    c_14_pop_bumper_left:
        number: pf1-5
        default_pulse_ms: 10
# ------------------------
# CONFIG:COILS - SAUCERS/VUKS
# ------------------------
    c_15_saucer_right:
        number: pf1-6
        default_pulse_ms: 10
# ------------------------
# CONFIG:COILS - VARI-TARGET
# ------------------------ 
    c_16_varitarget_reset:
        number: pf1-7
        default_pulse_ms: 5
# ------------------------
# CONFIG:COILS - PLAYFIELD Upper Node 1
# 1616 pf1
# J4 - 8 Coils
# C_17 to C_24
# ------------------------
#    c_17_SPARE:
#        number: pf1-8
#        default_pulse_ms: 1
#    c_18_SPARE:
#        number: pf1-9
#        default_pulse_ms: 1
#    c_19_SPARE:
#        number: pf1-10
#        default_pulse_ms: 1
#    c_20_SPARE:
#        number: pf1-11
#        default_pulse_ms: 1
#    c_21_SPARE:
#        number: pf1-12
#        default_pulse_ms: 1
#    c_22_SPARE:
#        number: pf1-13
#        default_pulse_ms: 1
#    c_23_SPARE:
#        number: pf1-14
#        default_pulse_ms: 1
#    c_24_SPARE:
#        number: pf1-15
#        default_pulse_ms: 1
#
# --------------------------------------------------------------------------------------------------------------------
#
#
# --------------------------------------------------------------------------------------------------------------------
# ------------------------
# CONFIG:COILS - PLAYFIELD Upper Node 3
# 1616 pf3
# J3 - 8 Coils
# C_25 to C_32
# ------------------------
#    c_25_SPARE:
#        number: pf3-0 
#        default_pulse_ms: 1
#    c_26_SPARE:
#        number: pf3-1 
#        default_pulse_ms: 1
#    c_27_SPARE:
#        number: pf3-2 
#        default_pulse_ms: 1
#    c_28_SPARE:
#        number: pf3-3 
#        default_pulse_ms: 1
# ------------------------
# CONFIG:COILS - SAUCERS/VUKS
# ------------------------
    c_29_saucer_left:
        number: pf3-4
        default_pulse_ms: 10
# ------------------------
# CONFIG:COILS - SINGLE DROP TARGET
# ------------------------ 
    c_30_single_drop_1_trip:
        number: pf3-5
        default_pulse_ms: 40
    c_31_single_drop_1_reset:
        number: pf3-6
        default_pulse_ms: 20
# ------------------------
# CONFIG:COILS - DROP TARGET 3-BANK
# ------------------------ 
    c_32_threebank_drop_reset:
        number: pf3-7
        default_pulse_ms: 10
# ------------------------
# CONFIG:COILS - PLAYFIELD Upper Node 3
# 1616 pf3
# J4 - 8 Coils
# C_33 to C_40
# ------------------------
# ------------------------
# CONFIG:COILS - DROP TARGETS
# ------------------------ 
    c_33_fourbank_drop_1_trip:
        number: pf3-8
        default_pulse_ms: 1
    c_34_fourbank_drop_2_trip:
        number: pf3-9
        default_pulse_ms: 1
    c_35_fourbank_drop_3_trip:
        number: pf3-10
        default_pulse_ms: 1
    c_36_fourbank_drop_4_trip:
        number: pf3-11
        default_pulse_ms: 1
    c_37_threebank_drop_1_trip:
        number: pf3-12
        default_pulse_ms: 1
    c_38_threebank_drop_2_trip:
        number: pf3-13
        default_pulse_ms: 1
    c_39_threebank_drop_3_trip:
        number: pf3-14
        default_pulse_ms: 1
    c_40_fourbank_drop_reset:
        number: pf3-15
        default_pulse_ms: 10
