#config_version=6
# config/device_config_iomap.yaml 
#------------------------
# CONFIG:SWITCHES:SINGLE - CABINET
# Temp change to PN: FP-I/O-0804--------FAST CABINET I/O Board PN: FP-I/O-0024----
# Node 1 - cab-x
switches:
#
# ------------------------
# J4 Coin Door
# ------------------------
    s_00_service_esc:
        number: cab-0
        tags: service_esc
    #    label: "Service - Escape"
    s_01_service_up:
        number: cab-1
        tags: service_up
    #    label: "Service - Up / Plus"
    s_02_service_down:
        number: cab-2
        tags: service_down
    #    label: "Service - Down / Minus"
    s_03_service_enter:
        number: cab-3
        tags: service_enter
    #    label: "Service - Enter"
#    s_04_coin_left:
#        number: cab-4
#        label: "Coin Slot - Left / 1"
#    s_05_coin_middle:
#        number: cab-5
#        label: "Coin Slot - Middle / x"
#    s_06_coin_right:
#        number: cab-6
#        label: "Coin Slot - Right / 3"
#    s_07_slam_tilt:
#        number: cab-7
#        tags: slam_tilt_warning
#        label: "Slam Tilt" 
# ------------------------
# J1 Cabinet Left
# ------------------------  
    s_08_left_flipper:
        number: cab-4
        tags: flipper_main_left, left_flipper, service_up
    #    label: "Flipper - Main - Left"
#    s_09_left_flipper_upper:
#        number: cab-9
#        tags: flipper_main_right, left_flipper
#        label: "Flipper - Main - Left"
#    s_10_left_secondary_button:
#        number: cab-10
#        tags: left_secondary_button
#        label: "Button - Left - Sec"
    s_11_start_button:
        number: cab-5
        tags: start
    #    label: "Start Button"
#    s_12_tilt_bob:
#        number: cab-12
#        tags: tilt_bob, tilt_warning
#    s_13_coin_door:
#        number: cab-13
#        label: "Coin Door"
#    s_14_roller_tilt:
#        number: cab-14
#        tags: roller_tilt_warning
#        label: "Roller Tilt"
#    s_15_SPARE:
#        number: cab-15
#        tags: SPARE_15
#        label: "SPARE_15" 
# ------------------------
# J9 Cabinet Right
# ------------------------      
    s_16_right_flipper:
        number: cab-6
        tags: flipper_main_right, right_flipper
    #    label: "Flipper - Main - Right"
    s_17_right_flipper_upper:
        number: cab-7
        tags: flipper_main_right, right_flipper, service_down
    #    label: "Flipper - Main - Right"
#    s_18_right_secondary_button:
#        number: 1-18
#        tags: right_secondary_button
#        label: "Button - Right - Sec"
#    s_19_cab_arrow_left:
#        number: 1-19
#        tags: cab_arrow_left, service_esc
#    s_20_cab_arrow_right:
#        number: 1-20
#        tags: cab_arrow_right, service_enter, action   
#    s_21_SPARE:
#        number: cab-21
#        tags: SPARE_21
#        label: "SPARE_21" 
#    s_22_SPARE:
#        number: cab-22
#        tags: SPARE_22
#        label: "SPARE_22" 
#    s_23_SPARE:
#        number: cab-23
#        tags: SPARE_23
#        label: "SPARE_23" 
#
#-------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------
#
#
# ------------------------
# CONFIG:SWITCHES:SINGLE - PLAYFIELD - PLAYFIELD BOTTOM THIRD
# FAST PLAYFIELD I/O Board PN: FP-I/O-3208
# pf2
# ------------------------
# ------------------------
#    J8
# ------------------------
    s_24_trough_1:
        number: pf2-0
        type: 'NC'
    #    label: "Trough - Position 1"
    s_25_trough_2:
        number: pf2-1
        type: 'NC'
    #    label: "Trough - Position 2"
    s_26_trough_3:
        number: pf2-2
        type: 'NC'
    #    label: "Trough - Position 3"
    s_27_trough_4:
        number: pf2-3
        type: 'NC'
    #    label: "Trough - Position 4"
    s_28_trough_5:
        number: pf2-4
        type: 'NC'
    #    label: "Trough - Position 5"
    s_29_trough_6:
        number: pf2-5
        type: 'NC'
    #    label: "Trough - Position 6"
    s_30_trough_jam:
        number: pf2-6
        type: 'NC'
    #    label: "Trough - Jam"
    s_31_plunger_lane:
        number: pf2-7
        tags: plunger_lane
    #    label: "Plunger Lane"
        ignore_window_ms: 500
# ------------------------
#    J3
# ------------------------
    s_32_right_inlane:
        number: pf2-8
        tags: right_return_lane, inlane, switch_hit
    #    label: "Return Lane - Right"
    s_33_right_outlane:
        number: pf2-9
        tags: right_out_lane, outlane, switch_hit
    #    label: "Outlane - Right"
    s_34_right_sling:
        number: pf2-10
        tags: slingshot, switch_hit, slingshot_r
    #    label: "Sling - Right"
    s_35_left_inlane:
        number: pf2-11
        tags: left_return_lane, inlane, switch_hit
    #    label: "Return Lane - Left"
    s_36_left_outlane:
        number: pf2-12
        tags: left_out_lane, outlane, switch_hit
    #    label: "Outlane - Left"
    s_37_left_sling:
        number: pf2-13
        tags: slingshot, switch_hit, slingshot_l
    #    label: "Sling - Left"
    s_38_star_rollover_bottom:
        number: pf2-14
        tags: rollover_bottom, rollover, switch_hit
    #    label: "Star Rollover - Bottom"
    s_39_star_rollover_top:
        number: pf2-15
        tags: rollover_top, rollover, switch_hit
    #    label: "Star Rollover - Top"
# ------------------------
#    J6
# ------------------------
    s_40_stand_up_target_5:
        number: pf2-16
        tags: standup_vari_left, standups, switch_hit, stars
    #    label: "Standup Target 5 Left Side Vari"
    s_41_stand_up_target_6:
        number: pf2-17
        tags: standup_vari_right, standups, switch_hit, stars
    #    label: "Standup Target 6 Right Side Vari"
    s_42_stand_up_target_1:
        number: pf2-18
        tags: standup_imp, standups, switch_hit, stars
    #    label: "Standup Target 1"
    s_43_stand_up_target_4:
        number: pf2-19
        tags: standup_pops, standups, switch_hit, stars
    #    label: "Standup Target 4"
    s_44_spinner_right:
        number: pf2-20
        type: 'NC'
        tags: spinner_r, spinners, switch_hit
#    s_45_SPARE:
#        number: pf2-21
#        tags: SPARE21
#    s_46_SPARE:
#        number: pf2-22
#        tags: SPARE22
#    s_47_SPARE:
#        number: pf2-23
#        tags: SPARE23
# ------------------------
# ------------------------
#    J9 - White wires
# ------------------------
#    s_48_SPARE:
#        number: pf2-24
#        tags:
#    s_49_SPARE:
#        number: pf2-25
#        tags:
#    s_50_SPARE:
#        number: pf2-26
#        tags:
#    s_51_SPARE:
#        number: pf2-27
#        tags:
#    s_52_SPARE:
#        number: pf2-28
#        tags:
#    s_53_SPARE:
#        number: pf2-29
#        tags:
#    s_54_SPARE:
#        number: pf2-30
#        tags:
#    s_55_SPARE:
#        number: pf2-31
#        tags: 
#
#-------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------
#
# ------------------------
# CONFIG:SWITCHES:SINGLE - PLAYFIELD
# FAST PLAYFIELD I/O Board PN: FP-I/O-1616
# pf1
# ------------------------
# J7 - Green Wires
# ------------------------
# CONFIG:SWITCHES:SINGLE - PLAYFIELD POP BUMPERS
# ------------------------
    s_56_pop_bumper_right:
        number: pf1-0
        tags: pop_bumper_right, pops, switch_hit
    #    label: "Pop Bumper Right"
        ignore_window_ms: 100
    s_57_pop_bumper_center:
        number: pf1-1
        tags: pop_bumper_center, pops, switch_hit
    #    label: "Pop Bumper Center"
        ignore_window_ms: 100
    s_58_pop_bumper_left:
        number: pf1-2
        tags: pop_bumper_left, pops, switch_hit
    #    label: "Pop Bumper left"
        ignore_window_ms: 100
    s_59_saucer_right:
        number: pf1-3
        tags: saucer_r, right_scoop, right_lock, scoop, teleport, switch_hit
        ignore_window_ms: 2000

# ------------------------
# CONFIG:SWITCHES:SINGLE - PLAYFIELD TOP LANES
# ------------------------
    s_60_top_lane_c:
        number: pf1-4
        tags: top_lane_right, lane_c, top_lanes, switch_hit
    s_61_top_lane_b:
        number: pf1-5
        tags: top_lane_mid, lane_b, top_lanes, switch_hit
    s_62_top_lane_a:
        number: pf1-6
        tags: top_lane_left, lane_a, top_lanes, switch_hit

# ------------------------
# CONFIG:SWITCHES:SINGLE - STANDUP TARGETS Singles
# ------------------------
    s_63_stand_up_target_3:
        number: pf1-7
        tags: standup_top, standups, switch_hit, stars

# ------------------------
# J8 - Orange Wires
# ------------------------
# ------------------------
# CONFIG:SWITCHES:SINGLE - VARI-TARGET
# ------------------------
    s_64_varitarget_position_1:
        number: pf1-8
        type: NC
        tags: vari_1, vari_home, vari
    #    label: "VariTarget - Position 1"
    s_65_varitarget_position_2:
        number: pf1-9
        tags: vari_2, vari, switch_hit
    #    label: "VariTarget - Position 2"
    s_66_varitarget_position_3:
        number: pf1-10
        tags: vari_3, vari, switch_hit
    #    label: "VariTarget - Position 3"
    s_67_varitarget_position_4:
        number: pf1-11
        tags: vari_4, vari, switch_hit
    #    label: "VariTarget - Position 4"
    s_68_varitarget_position_5:
        number: pf1-12
        tags: vari_5, vari, switch_hit
    #    label: "VariTarget - Position 5"
    s_69_varitarget_position_6:
        number: pf1-13
        tags: vari_6, vari, switch_hit
    #    label: "VariTarget - Position 6"
    s_70_varitarget_position_7:
        number: pf1-14
        tags: vari_7, vari, vari_end, switch_hit
    #    label: "VariTarget - Position 7"
# ------------------------
# CONFIG:SWITCHES:SINGLE - SPINNERS
# ------------------------
    s_71_spinner_left:
        number: pf1-15
        type: 'NC'
        tags: spinner_l, spinners, switch_hit
    #    label: "Spinner - Left"
#
#-------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------
#-------------------------------------------------------------------------------------------
#
# ------------------------
# CONFIG:SWITCHES:SINGLE
# FAST PLAYFIELD I/O Board PN: FP-I/O-1616
# pf3
# ------------------------
# J7 - Green Wires
# ------------------------
# ------------------------
# CONFIG:SWITCHES:SINGLE - DROP TARGET SINGLE
# ------------------------
    s_72_single_drop_1:
        number: pf3-0
        tags: single_drop_hit, drop_8, drop_target, drops, switch_hit
    #    label: "Single Drop 1"
        ignore_window_ms: 300
# ------------------------
# CONFIG:SWITCHES:SINGLE - DROP TARGET 7-BANK
# ------------------------
    s_73_fourbank_drop_1:
        number: pf3-1
        tags: fourbank_drop_1, drop_1, fourbank, drop_target, drops, switch_hit
        ignore_window_ms: 300
    s_74_fourbank_drop_2:
        number: pf3-2
        tags: fourbank_drop_2, drop_2, fourbank, drop_target, drops, switch_hit
        ignore_window_ms: 300
    s_75_fourbank_drop_3:
        number: pf3-3
        tags: fourbank_drop_3, drop_3, fourbank, drop_target, drops, switch_hit
        ignore_window_ms: 300
    s_76_fourbank_drop_4:
        number: pf3-4
        tags: fourbank_drop_4, drop_4, fourbank, drop_target, drops, switch_hit
        ignore_window_ms: 300
    s_77_threebank_drop_1:
        number: pf3-5
        tags: threebank_drop_1, drop_5, threebank, drop_target, drops, switch_hit
        ignore_window_ms: 300
    s_78_threebank_drop_2:
        number: pf3-6
        tags: threebank_drop_2, drop_6, threebank, drop_target, drops, switch_hit
        ignore_window_ms: 300
    s_79_threebank_drop_3:
        number: pf3-7
        tags: threebank_drop_3, drop_7, threebank, drop_target, drops, switch_hit
        ignore_window_ms: 300
# -------------------------------------------------
# CONFIG:SWITCHES:SINGLE - STANDUP TARGET after VUK
# -------------------------------------------------
    s_80_stand_up_target_2:
        number: pf3-8
        tags: standup_power, standups, switch_hit, stars
# ----------------------------------------
# CONFIG:SWITCHES:SINGLE - SAUCERS
#-----------------------------------------
    s_81_saucer_left:
        number: pf3-9
        ignore_window_ms: 2000
        tags: saucer_l, left_scoop, left_lock, scoop, switch_hit
# ----------------------------------------
# CONFIG:SWITCHES: 6-BANK
#-----------------------------------------
    s_82_stand_up_target_bank_1:
        number: pf3-10
        tags: target_1, target_green, targets, switch_hit
    s_83_stand_up_target_bank_2:
        number: pf3-11
        tags: target_2, target_blue, targets, switch_hit
    s_84_stand_up_target_bank_3:
        number: pf3-12
        tags: target_3, target_red, targets, switch_hit
    s_85_stand_up_target_bank_4:
        number: pf3-13
        tags: target_4, target_red, targets, switch_hit
    s_86_stand_up_target_bank_5:
        number: pf3-14
        tags: target_5, target_blue, targets, switch_hit
    s_87_stand_up_target_bank_6:
        number: pf3-15
        tags: target_6, target_green, targets, switch_hit